services:
  db:
    image: docker.io/library/mysql:8.0
    container_name: piepydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: piepydb

    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    image: piepyimage
    container_name: piepyapp
    tty: true

    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: piepydb

    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata: