services:
  app:
    build: .
    image: piepyimage
    container_name: piepyapp
    tty: true

    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: piepydb

    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata:
