services:
  app:
    build: .
    image: piepy-image
    container_name: piepy-app
    tty: true

    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      LOG_FILE: ${LOG_FILE}

    env_file:
      - .env
