[project]
name = "piepy"
version = "0.1.0"
authors = [
  { name="ityeri", email="ityeri9@gmail.com" },
]
description = "파이봇"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "discord.py>=2.6.4,<3.0.0",
    "yspy @ git+https://github.com/ityeri/yspy.git",
    "dotenv>=0.9.9,<1.0.0",
    "pytubefix>=10.3.6,<11.0.0",
    "davey>=0.1.6",
]

[project.urls]
Homepage = "https://github.com/ityeri/piepy"
Issues = "https://github.com/ityeri/piepy/issues"

[build-system]
requires = ["uv_build>=0.11.8,<0.12"]
build-backend = "uv_build"
